/*
  Warnings:

  - The values [ADMIN_LOGIN,ADMIN_LOGOUT,USER_LOGIN,USER_LOGOUT] on the enum `ActivityAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActivityAction_new" AS ENUM ('LOGIN', 'LOGOUT', 'FORGOT_PASSWORD_REQUEST', 'RESET_PASSWORD_SUCCESS', 'ADMIN_CREATE_DESTINATION', 'ADMIN_UPDATE_DESTINATION', 'ADMIN_DELETE_DESTINATION', 'ADMIN_CREATE_CATEGORY', 'ADMIN_UPDATE_CATEGORY', 'ADMIN_DELETE_CATEGORY', 'ADMIN_CREATE_REGION', 'ADMIN_UPDATE_REGION', 'ADMIN_DELETE_REGION', 'ADMIN_CREATE_PICKUP', 'ADMIN_UPDATE_PICKUP', 'ADMIN_DELETE_PICKUP', 'ADMIN_UPDATE_USER', 'ADMIN_DELETE_USER', 'ADMIN_APPROVE_TESTIMONI', 'ADMIN_REJECT_TESTIMONI', 'ADMIN_UPDATE_TESTIMONI', 'ADMIN_DELETE_TESTIMONI', 'ADMIN_CREATE_BANNER', 'ADMIN_UPDATE_BANNER', 'ADMIN_DELETE_BANNER', 'ADMIN_CREATE_ABOUT', 'ADMIN_UPDATE_ABOUT', 'ADMIN_DELETE_ABOUT', 'ADMIN_CREATE_VALUE', 'ADMIN_UPDATE_VALUE', 'ADMIN_DELETE_VALUE', 'ADMIN_CREATE_TEAM', 'ADMIN_UPDATE_TEAM', 'ADMIN_DELETE_TEAM', 'ADMIN_UPDATE_PROFILE', 'USER_UPDATE_PROFILE', 'USER_CREATE_ORDER', 'USER_PAYMENT_SUCCESS', 'USER_PAYMENT_FAILED');
ALTER TABLE "tb_activity_logs" ALTER COLUMN "action" TYPE "ActivityAction_new" USING ("action"::text::"ActivityAction_new");
ALTER TYPE "ActivityAction" RENAME TO "ActivityAction_old";
ALTER TYPE "ActivityAction_new" RENAME TO "ActivityAction";
DROP TYPE "public"."ActivityAction_old";
COMMIT;
