import { ReactNode } from "react";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import NavBar from "./components/NavBar";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import Footer from "./components/Footer";
import "@/app/globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



export const metadata = {
  title: "LamiGo - Jelajah Alam Lampung",
  description: "Temukan destinasi terbaik dan pesan tiket dengan mudah",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="id">
      <body className="antialiased text-slate-900 bg-white">
        {/* <NavBar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
