-- CreateEnum
CREATE TYPE "ActivityAction" AS ENUM ('ADMIN_LOGIN', 'ADMIN_LOGOUT', 'USER_LOGIN', 'USER_LOGOUT', 'ADMIN_CREATE_DESTINATION', 'ADMIN_UPDATE_DESTINATION', 'ADMIN_DELETE_DESTINATION', 'ADMIN_CREATE_CATEGORY', 'ADMIN_UPDATE_CATEGORY', 'ADMIN_DELETE_CATEGORY', 'ADMIN_CREATE_REGION', 'ADMIN_UPDATE_REGION', 'ADMIN_DELETE_REGION', 'ADMIN_CREATE_PICKUP', 'ADMIN_UPDATE_PICKUP', 'ADMIN_DELETE_PICKUP', 'ADMIN_UPDATE_USER', 'ADMIN_DELETE_USER', 'ADMIN_APPROVE_TESTIMONI', 'ADMIN_REJECT_TESTIMONI', 'ADMIN_UPDATE_TESTIMONI', 'ADMIN_DELETE_TESTIMONI', 'ADMIN_CREATE_BANNER', 'ADMIN_UPDATE_BANNER', 'ADMIN_DELETE_BANNER', 'ADMIN_CREATE_ABOUT', 'ADMIN_UPDATE_ABOUT', 'ADMIN_DELETE_ABOUT', 'ADMIN_CREATE_VALUE', 'ADMIN_UPDATE_VALUE', 'ADMIN_DELETE_VALUE', 'ADMIN_CREATE_TEAM', 'ADMIN_UPDATE_TEAM', 'ADMIN_DELETE_TEAM', 'ADMIN_UPDATE_PROFILE', 'USER_UPDATE_PROFILE', 'USER_CREATE_ORDER', 'USER_PAYMENT_SUCCESS', 'USER_PAYMENT_FAILED');

-- CreateTable
CREATE TABLE "tb_activity_logs" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER,
    "role" "Role" NOT NULL,
    "action" "ActivityAction" NOT NULL,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tb_activity_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tb_activity_logs_userId_idx" ON "tb_activity_logs"("userId");

-- CreateIndex
CREATE INDEX "tb_activity_logs_role_idx" ON "tb_activity_logs"("role");

-- CreateIndex
CREATE INDEX "tb_activity_logs_action_idx" ON "tb_activity_logs"("action");

-- CreateIndex
CREATE INDEX "tb_activity_logs_createdAt_idx" ON "tb_activity_logs"("createdAt");

-- AddForeignKey
ALTER TABLE "tb_activity_logs" ADD CONSTRAINT "tb_activity_logs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "tb_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
